import { siteConfig } from "@/config/site";

export type ExperiencePhase =
  "intro" | "works" | "vision-transition" | "vision" | "showcase-transition" | "showcase" | "outro";

export const experienceConfig = {
  brand: {
    name: siteConfig.name,
    shortName: siteConfig.shortName,
    wordmark: ["GÖKNUR", "UYGUR"] as const,
  },
  chamber: {
    radius: 10.5,
    height: 7.4,
    depth: 15,
    gridOpacity: 0.075,
    panelOpacity: 0.12,
  },
  orbit: {
    radiusX: 6.15,
    radiusZ: 3.9,
    inclinationDegrees: 31,
    centerX: 0.42,
    centerY: 1.55,
    autoRotationSpeed: 0.065,
    pointerVelocityStrength: 0.22,
    dragSensitivity: 0.0046,
    velocityDamping: 4.6,
    velocityResponsiveness: 3.8,
    frontScale: 1.08,
    sideScale: 0.82,
    backScale: 0.64,
    frontOpacity: 1,
    sideOpacity: 0.76,
    backOpacity: 0.36,
    frontAnchorX: 0.53,
    frontAnchorY: 0.51,
  },
  cards: {
    worldWidth: 3.08,
    worldHeight: 1.75,
    desktopMaxWidth: 780,
    tabletMaxWidth: 540,
    mobileMaxWidth: 326,
  },
  pointerField: {
    radius: 0.43,
    intensity: 0.9,
    refractionStrength: 0.025,
    displacement: 0.14,
    surfaceOpacity: 0.98,
    projectRadius: 0.35,
    projectIntensity: 1.08,
    projectRefractionStrength: 0.05,
    projectDisplacement: 0.24,
  },
  transitions: {
    introToWorksDuration: 1.2,
    curvedWipeDuration: 1,
    projectOpenDuration: 0.55,
  },
  colors: {
    river: "#9bcbe3",
    wind: "#fff8e8",
    fennelDeep: "#a7cdb0",
    fennelSoft: "#f4ce63",
    sandWhite: "#fff8e8",
    sunset: "#e9785f",
    night: "#fff8e8",
    projects: "#6f8d94",
    vision: "#a7cdb0",
    showcase: "#f4ce63",
    packages: "#fff8e8",
    contact: "#e9785f",
    graphite: "#20292d",
    mineral: "#fff8e8",
    smokedNavy: "#9bcbe3",
    taupe: "#a7cdb0",
    warmStone: "#a7cdb0",
    processWall: "#f4ce63",
    processFloor: "#9bcbe3",
    processMetal: "#20292d",
    champagne: "#f4ce63",
    ivory: "#fff8e8",
    olive: "#a7cdb0",
    violet: "#a7cdb0",
    blue: "#8fb2bd",
    magenta: "#b97868",
    amber: "#d8c394",
    cyan: "#dce7e4",
    projectPomegranate: "#49656e",
    projectCoral: "#b97868",
    projectSun: "#d8c394",
    projectCream: "#e9e4d8",
    projectCeladon: "#a9bca9",
  },
  camera: {
    intro: [0, 0.18, 8.7] as const,
    works: [0.38, 0.34, 9.45] as const,
    vision: [0, 0.18, 9.8] as const,
  },
} as const;
