import type { DesignPackage } from "@/types";

export const fallbackPackages = [
  {
    slug: "three-question-package",
    title: "3 Soru Paketi",
    scopeLabel: "3 odaklı soru",
    deliveryMode: "Dijital ürün",
    summary:
      "Evini yenilerken birkaç kritik konuda profesyonel onay ve net bir mimari yön arayanlar için odaklı danışmanlık paketi.",
    benefit:
      "Kararsızlığı azaltır, hata yapma endişesini hafifletir ve kısa sürede uygulanabilir bir mimari yol haritası sunar.",
    pricingLabel: "3.000 TL",
    pricingNote: "Shopier'da listelenen dijital ürün fiyatı.",
    image: {
      src: "/images/packages/three-question-package.webp",
      alt: "Üç ayrı karar kartı, kat planı ve malzeme örnekleri bulunan mimari danışmanlık masası",
      width: 1440,
      height: 960,
    },
    scopeItems: ["3 odaklı mimari soru", "Profesyonel karar desteği", "Net mimari yol haritası"],
    examples: [
      "Evini yenileyenler",
      "Birkaç konuda profesyonel onay isteyenler",
      "Hızlı mimari destek arayanlar",
    ],
    shopierUrl: "https://www.shopier.com/mimargoknuruygur/41546206",
    showOnHomepage: true,
    order: 1,
  },
  {
    slug: "accessory-styling-package",
    title: "Aksesuar & Styling Paketi",
    scopeLabel: "Aksesuar & styling",
    deliveryMode: "Dijital ürün",
    summary: "Mekânın tamamlayıcı aksesuar ve styling kararlarına odaklanan dijital ürün.",
    benefit:
      "Mekândaki tamamlayıcı parçaları daha dengeli, tutarlı ve özenli bir görünümde bir araya getirmenize yardımcı olur.",
    pricingLabel: "4.800 TL",
    pricingNote: "Shopier'da listelenen dijital ürün fiyatı.",
    image: {
      src: "/images/packages/accessory-styling-package.webp",
      alt: "Sanat eseri, aydınlatma, seramik ve tekstillerle dengeli biçimde stillenmiş konsol",
      width: 1440,
      height: 960,
    },
    scopeItems: ["Aksesuar seçimi odağı", "Mekânsal styling odağı"],
    scopeBasis: "Shopier ürün sayfasında ayrıntılı kapsam açıklaması yayımlanmamıştır.",
    shopierUrl: "https://www.shopier.com/mimargoknuruygur/39387499",
    showOnHomepage: false,
    order: 2,
  },
  {
    slug: "online-consulting",
    title: "Online Danışmanlık",
    scopeLabel: "Uzaktan danışmanlık",
    deliveryMode: "Dijital ürün",
    summary:
      "Esinlenme panosu, renk danışmanlığı, ürün ve aksesuar seçimlerini bir araya getiren online tasarım hizmeti.",
    benefit:
      "Renk ve alışveriş kararlarını tek bir tasarım dili altında toplayarak uygulanabilir bir seçim planına dönüştürür.",
    pricingLabel: "6.000 TL",
    pricingNote: "Shopier'da listelenen dijital ürün fiyatı.",
    image: {
      src: "/images/packages/online-consulting-package.webp",
      alt: "Dizüstü bilgisayar, esinlenme panosu, renk kartları ve malzeme örnekleriyle online tasarım masası",
      width: 1440,
      height: 960,
    },
    scopeItems: ["Esinlenme panosu", "Renk danışmanlığı", "Ürün seçimi", "Aksesuar seçimi"],
    shopierUrl: "https://www.shopier.com/mimargoknuruygur/35166631",
    showOnHomepage: true,
    order: 3,
  },
  {
    slug: "product-design",
    title: "Ürün Tasarımı",
    scopeLabel: "1 özel ürün",
    deliveryMode: "Dijital ürün",
    summary:
      "Kitaplık, ünite, portmanto, depolama veya giysi dolabı gibi seçilen tek bir ürün için ölçülü tasarım hizmeti.",
    benefit:
      "İhtiyacınıza göre şekillenen özel ürünü, imalat öncesinde ölçüsü, görünümü, malzemesi ve rengiyle değerlendirmenizi sağlar.",
    pricingLabel: "6.900 TL",
    pricingNote: "Shopier'da listelenen dijital ürün fiyatı.",
    image: {
      src: "/images/packages/product-design-shopier.webp",
      alt: "Ölçülü çizimi, maketi ve malzeme örnekleriyle özel tasarım depolama ve medya ünitesi",
      width: 1440,
      height: 960,
    },
    scopeItems: [
      "Seçilen 1 ürünün 2D ölçülü çizimleri",
      "Ürünün 3D görselleri",
      "Malzeme ve renk alternatifleri",
      "3D tesliminden sonra 1 revize hakkı",
    ],
    examples: ["Kitaplık", "Ünite", "Portmanto", "Depolama", "Giysi dolabı"],
    presentationFormats: ["2D", "3D"],
    shopierUrl: "https://www.shopier.com/mimargoknuruygur/43321697",
    showOnHomepage: true,
    order: 4,
  },
  {
    slug: "online-layout-consulting-2d",
    title: "Online Danışmanlık — 2D Yerleşim",
    scopeLabel: "2D yerleşim desteği",
    deliveryMode: "Dijital ürün",
    summary:
      "Mobilya yerleşiminde veya oda ölçüsüne uygun mobilya seçiminde zorlananlar için 2 boyutlu yerleşim odaklı online paket.",
    benefit:
      "Mobilyaları satın almadan veya taşımadan önce ölçü, yerleşim ve dolaşım kararlarını okunaklı bir plan üzerinde netleştirir.",
    pricingLabel: "7.000 TL",
    pricingNote: "Shopier'da listelenen dijital ürün fiyatı.",
    image: {
      src: "/images/packages/online-layout-2d.webp",
      alt: "Mobilya yerleşimi ve dolaşım alanları gösterilen iki boyutlu konut planı",
      width: 1440,
      height: 960,
    },
    scopeItems: ["2D mobilya yerleşimi", "Oda ölçüsüne uygun mobilya seçimi", "Online yönlendirme"],
    presentationFormats: ["2D"],
    exclusions: ["3D çizim hizmeti"],
    shopierUrl: "https://www.shopier.com/mimargoknuruygur/35164826",
    showOnHomepage: false,
    order: 5,
  },
  {
    slug: "laundry-room-design",
    title: "Çamaşır Odası Tasarımı",
    scopeLabel: "Tek çamaşır odası",
    deliveryMode: "Dijital ürün",
    summary:
      "Çamaşır odasının detaylı analizi ve bu mekâna yönelik geliştirilen tasarımın 2D ve 3D sunumlarını kapsar.",
    benefit:
      "Yıkama, kurutma, katlama ve depolama ihtiyaçlarını daha düzenli ve verimli bir mekânsal akışta birleştirir.",
    pricingLabel: "7.750 TL",
    pricingNote: "Shopier'da listelenen dijital ürün fiyatı.",
    image: {
      src: "/images/packages/laundry-room-design.webp",
      alt: "Depolama, katlama tezgâhı ve asma alanı bulunan düzenli çağdaş çamaşır odası",
      width: 1440,
      height: 960,
    },
    scopeItems: [
      "Detaylı mekân analizi",
      "2D ve 3D sunumlar",
      "1 revize hakkı",
      "Revize için ilave 2 iş günü",
    ],
    presentationFormats: ["2D", "3D"],
    shopierUrl: "https://www.shopier.com/mimargoknuruygur/46064208",
    showOnHomepage: false,
    order: 6,
  },
  {
    slug: "bathroom-design",
    title: "Banyo Tasarımı",
    scopeLabel: "Tek banyo",
    deliveryMode: "Dijital ürün",
    summary:
      "Banyonun detaylı analizi ve bu mekâna yönelik geliştirilen tasarımın 2D ve 3D sunumlarını kapsar.",
    benefit:
      "Yerleşim, depolama, ürün ve malzeme kararlarını uygulama öncesinde bütünlüklü bir banyo tasarımında buluşturur.",
    pricingLabel: "9.000 TL",
    pricingNote: "Shopier'da listelenen dijital ürün fiyatı.",
    image: {
      src: "/images/packages/bathroom-design.webp",
      alt: "Özel dolap, katmanlı aydınlatma ve duş alanıyla tasarlanmış çağdaş banyo",
      width: 1440,
      height: 960,
    },
    scopeItems: [
      "Detaylı mekân analizi",
      "2D ve 3D sunumlar",
      "1 revize hakkı",
      "Revizede 1 ürün, yerleşim planı veya 3 ürün seçimi güncellemesinden biri",
      "Revize için ilave 3 iş günü",
    ],
    presentationFormats: ["2D", "3D"],
    shopierUrl: "https://www.shopier.com/mimargoknuruygur/43322430",
    showOnHomepage: false,
    order: 7,
  },
  {
    slug: "bedroom-design",
    title: "Yatak Odası Tasarımı",
    scopeLabel: "Tek yatak odası",
    deliveryMode: "Dijital ürün",
    summary:
      "Yatak odasının detaylı analizi ve bu mekâna yönelik geliştirilen tasarımın 2D ve 3D sunumlarını kapsar.",
    benefit:
      "Uyku, depolama, hazırlanma ve dolaşım ihtiyaçlarını sakin ve tutarlı bir oda düzeninde birleştirir.",
    pricingLabel: "10.500 TL",
    pricingNote: "Shopier'da listelenen dijital ürün fiyatı.",
    image: {
      src: "/images/packages/bedroom-design.webp",
      alt: "Bütünleşik gardırop, makyaj masası ve katmanlı tekstillerle tasarlanmış sakin yatak odası",
      width: 1440,
      height: 960,
    },
    scopeItems: [
      "Detaylı mekân analizi",
      "2D ve 3D sunumlar",
      "1 revize hakkı",
      "Revizede 1 ürün, yerleşim planı veya 3 ürün seçimi güncellemesinden biri",
      "Revize için ilave 3 iş günü",
    ],
    presentationFormats: ["2D", "3D"],
    shopierUrl: "https://www.shopier.com/mimargoknuruygur/42802533",
    showOnHomepage: false,
    order: 8,
  },
  {
    slug: "living-room-design",
    title: "Salon / Oturma Odası Tasarımı",
    scopeLabel: "Tek yaşam alanı",
    deliveryMode: "Dijital ürün",
    summary:
      "Salon veya oturma odasının detaylı analizi ve bu mekâna yönelik tasarımın 2D ve 3D sunumlarını kapsar.",
    benefit:
      "Oturma düzeni, dolaşım, depolama ve ürün seçimlerini dengeli ve davetkâr bir yaşam alanına dönüştürür.",
    pricingLabel: "10.500 TL",
    pricingNote: "Shopier'da listelenen dijital ürün fiyatı.",
    image: {
      src: "/images/packages/living-room-design.webp",
      alt: "Oturma bölgeleri ve özel medya duvarıyla tasarlanmış çağdaş salon",
      width: 1440,
      height: 960,
    },
    scopeItems: [
      "Detaylı mekân analizi",
      "2D ve 3D sunumlar",
      "1 revize hakkı",
      "Revizede 1 ürün, yerleşim planı veya 3 ürün seçimi güncellemesinden biri",
      "Revize için ilave 3 iş günü",
    ],
    presentationFormats: ["2D", "3D"],
    shopierUrl: "https://www.shopier.com/mimargoknuruygur/42802782",
    showOnHomepage: false,
    order: 9,
  },
  {
    slug: "kitchen-design",
    title: "Mutfak Tasarımı",
    scopeLabel: "Tek mutfak",
    deliveryMode: "Dijital ürün",
    summary:
      "Mutfağın detaylı analizi ve bu mekâna yönelik geliştirilen tasarımın 2D ve 3D sunumlarını kapsar.",
    benefit:
      "Depolama, hazırlık, pişirme ve günlük kullanım ihtiyaçlarını daha verimli ve tutarlı bir mutfak kurgusunda birleştirir.",
    pricingLabel: "10.850 TL",
    pricingNote: "Shopier'da listelenen dijital ürün fiyatı.",
    image: {
      src: "/images/packages/kitchen-design.webp",
      alt: "Ada, bütünleşik depolama ve kahve köşesiyle tasarlanmış çağdaş mutfak",
      width: 1440,
      height: 960,
    },
    scopeItems: [
      "Detaylı mekân analizi",
      "2D ve 3D sunumlar",
      "1 revize hakkı",
      "Revizede 1 ürün, yerleşim planı veya 3 ürün seçimi güncellemesinden biri",
      "Revize için ilave 3 iş günü",
    ],
    presentationFormats: ["2D", "3D"],
    shopierUrl: "https://www.shopier.com/mimargoknuruygur/35165675",
    showOnHomepage: false,
    order: 10,
  },
  {
    slug: "residential-package",
    title: "Konut Paketi",
    scopeLabel: "1+1 · 2+1 · 3+1",
    deliveryMode: "Dijital ürün",
    summary:
      "Konutun büyüklüğüne göre 1+1, 2+1 ve 3+1 seçenekleri bulunan, 2D ve 3D sunumlu bütüncül tasarım paketi.",
    benefit:
      "Evin farklı mekânlarını tek tek çözmek yerine yerleşim, malzeme ve atmosfer kararlarını bütüncül bir tasarım dili altında toplar.",
    pricingLabel: "29.000 TL'den",
    pricingNote: "1+1 29.000 TL · 2+1 39.000 TL · 3+1 48.000 TL",
    priceOptions: [
      {
        label: "1+1 · 70 m²'ye kadar",
        price: "29.000 TL",
        href: "https://www.shopier.com/mimargoknuruygur/35166268",
      },
      {
        label: "2+1 · 90 m²'ye kadar",
        price: "39.000 TL",
        href: "https://www.shopier.com/mimargoknuruygur/47122455",
      },
      {
        label: "3+1 · 120 m²'ye kadar",
        price: "48.000 TL",
        href: "https://www.shopier.com/mimargoknuruygur/48939147",
      },
    ],
    image: {
      src: "/images/packages/residential-package.webp",
      alt: "Farklı büyüklüklerde konut seçeneklerini gösteren bütüncül apartman kesit maketi",
      width: 1440,
      height: 960,
    },
    scopeItems: [
      "Metrekareye göre değişen paket kapsamı",
      "2D ve 3D sunumlar",
      "1+1 seçeneğinde 30 m² ile sınırlı revize",
      "2+1 ve 3+1 seçeneklerinde her mekân için 1 mobilya veya 10 m² alan revizesi",
    ],
    presentationFormats: ["2D", "3D"],
    scopeBasis: "Paket seçeneği konut tipi ve azami metrekareye göre belirlenir.",
    shopierUrl: "https://www.shopier.com/mimargoknuruygur/35166268",
    showOnHomepage: false,
    order: 11,
  },
] as const satisfies readonly DesignPackage[];

export const getFallbackPackageBySlug = (slug: string): DesignPackage | undefined =>
  fallbackPackages.find((designPackage) => designPackage.slug === slug);
